import * as React from 'react';
import Box from '@mui/material/Box';
import TextField from '@mui/material/TextField';
import Autocomplete from '@mui/material/Autocomplete';
import { LocationCity } from '@mui/icons-material';

export default function CountrySelect(onCityChange) {
  const [city,setCity]=React.useState("")
  const cities = [
    'Beirut',
    'Tripoli',
    'Sidon',
    'Tyre',
    'Byblos',
    'Jounieh',
    'Baalbek',
    'Nabatieh',
    'Zahle',
    'Anjar',
    'Batroun',
    'Bcharré',
    'Chekka',
    'Bhamdoun',
    'Jbeil',
    'Aley',
    'Baabda',
    'Zouk Mosbeh',
    'Choueifat',
    'Saida',
    'Ras Baalbek',
    'Deir el Qamar',
    'Jiyeh',
    'Zahlé',
    'Marjayoun',
    'Majdal Anjar',
    'Bint Jbeil',
    'Marjeyoun',
    'Dahr el Baydar',
    'Mtein',
    'Moukhtara',
    'Barouk',
    'Kfardebian',
    'Damour',
    'Hammana',
    'Beiteddine',
    'Bzommar',
    'Bdadoun',
    'Mkalles',
    'Dik El Mehdi',
    'Rayfoun',
    'Rabieh',
    'Broumana',
    'Jeita',
    'Naameh',
    'Ain Saade',
    'Dbayeh',
    'Sin El Fil',
    'Chiyah',
    'Fanar',
    'Zalka',
    'Jal El Dib',
    'Bsalim',
    'Antelias',
    'Mkalles',
    'Awkar',
    'Adma',
    'Dora',
    'Zahleh',
    'Hermel',
    'Jal Eddib',
    'Qornayel',
    'Zouk Mikael',
    'Hrajel',
    'Bikfaya',
    'Jal El Dhour',
    'Hosrayel',
    'Nahr Ibrahim',
    'Ain El Remmaneh',
    'Mazraat Yachouh',
    'Kfarhbab',
    'Ajaltoun',
    'Broummana',
    'Hboub',
    'Nabaa',
    'Cornet Chehwan',
    'Naccache',
    'Yarzeh',
    'Jdaide',
    'Jal El Bahr',
    'Dahr El Ain',
    'Mastita',
    'Adonis',
    'Achrafieh',
    'Dora',
    'Badaro',
    'Mansourieh',
    'Hazmieh',
    'Mkalles',
    'Jdeideh',
    'Bauchrieh',
    'Mazraat Yachouh',
    'Roumieh',
    'Beit Mery',
    'Sodeco',
    'Bir Hassan',
    'Mar Elias',
    'Kaskas',
    'Sanayeh',
    'Museum',
    'Jnah',
    'Verdun',
    'Clemenceau',
    'Ras Beirut',
    'Hamra',
    'Cornsiche Mazraa',
    'Geitawi',
    'Bourj Hammoud',
    'Dekwaneh',
    'Bourj Abi Haidar',
    'Mar Mikhael',
    'Karantina',
    'Sin El Fil',
    'Mazraa',
    'Achrafieh',
    'Horch Tabet',
    'Zalka',
    'Dora',
    'Dekwaneh',
    'Bouchrieh',
    'Mkalles',
    'Jdeideh',
    'Zouk Mosbeh',
    'Bauchrieh',
    'Furn El Chebbak',
    'Sahel Alma',
    'Mansourieh',
    'Sin El Fil',
    'Zouk Mikael',
    'Bkennaya',
    'Awkar',
    'Mazraat Yachouh',
    'Dekouaneh',
    'Jal El Dib',
    'Mkalles',
    'Fanar',
    'Hazmieh',
    'Rabieh',
    'Yarzeh',
    'Bsalim',
    'Naccache',
    'Dora',
    'Zalka',
    'Sin El Fil',
    'Dbayeh',
    'Baabdat',
    'Jdeideh',
    'Sakiet El Janzir',
    'Bauchrieh',
    'Antelias',
    'Bikfaya',
    'Mrouj',
    'Broummana',
    'Dora',
    'Sin El Fil',
    'Bauchrieh',
    'Bsalim',
    'Mkalles',
    'Antelias',
    'Naccache',
    'Dbayeh',
    'Dora',
    'Mazraat Yachouh',
    'Zalka',
    'Sin El Fil',
    'Zouk Mikael',
    'Antelias',
    'Sarba',
    'Naccache',
    'Mkalles',
    'Bsalim',
    'Zouk Mosbeh',
    'Jal El Dib',
    'Hazmieh',
    'Fanar',
    'Rabieh',
    'Sakiet El Janzir',
    'Awkar',
    'Sin El Fil',
    'Bikfaya',
    'Broummana',
    'Antelias',
    'Naccache',
    'Dbayeh',
    'Dora',
    'Mkalles',
    'Zalka',
    'Sin El Fil',
    'Jal El Dib',
    'Hazmieh',
    'Bsalim',
    'Rabieh',
    'Awkar',
    'Dora',
    'Zouk Mosbeh',
    'Sarba',
    'Mkalles',
    'Naccache',
    'Sin El Fil',
    'Zalka',
    'Dbayeh',
    'Antelias',
    'Dekwaneh',
    'Fanar',
    'Bsalim',
    'Jal El Dib',
    'Nahr El Mot',
    'Sarba',
    'Naccache',
    'Zouk Mosbeh',
    'Mkalles',
    'Antelias',
    'Sin El Fil',
    'Dbayeh',
    'Dora',
    'Zalka',
    'Jal El Dib',
    'Hazmieh',
    'Bsalim',
    'Awkar',
    'Fanar',
    'Rabieh',
    'Mazraat Yachouh',
    'Sarba',
    'Naccache',
    'Zouk Mosbeh',
    'Mkalles',
    'Antelias',
    'Sin El Fil',
    'Dbayeh',
    'Dora',
    'Zalka',
    'Jal El Dib',
    'Hazmieh',
    'Bsalim',
    'Awkar',
    'Fanar',
    'Rabieh',
    'Mazraat Yachouh',
    'Sarba',
    'Naccache',
    'Zouk Mosbeh',
    'Mkalles',
    'Antelias',
    'Sin El Fil',
    'Dbayeh',
    'Dora',
    'Zalka',
    'Jal El Dib',
    'Hazmieh',
    'Bsalim',
    'Awkar',
    'Fanar',
    'Rabieh',
    'Mazraat Yachouh',
    'Sarba',
    'Naccache',
    'Zouk Mosbeh',
    'Mkalles',
    'Antelias',
    'Sin El Fil',
    'Dbayeh',
    'Dora',
    'Zalka',
    'Jal El Dib',
    'Hazmieh',
    'Bsalim',
    'Awkar',
    'Fanar',
    'Rabieh',
    'Mazraat Yachouh',
    'Sarba',
    'Naccache',
    'Zouk Mosbeh',
    'Mkalles',
    'Antelias',
    'Sin El Fil',
    'Dbayeh',
    'Dora',
    'Zalka',
    'Jal El Dib',
    'Hazmieh',
    'Bsalim',
    'Awkar',
    'Fanar',
    'Rabieh',
    'Mazraat Yachouh',
    'Sarba',
    'Naccache',
    'Zouk Mosbeh',
    'Mkalles',
    'Antelias',
    'Sin El Fil',
    'Dbayeh',
    'Dora',
    'Zalka',
    'Jal El Dib',
    'Hazmieh',
    'Bsalim',
    'Awkar',
    'Fanar',
    'Rabieh',
    'Mazraat Yachouh',
    'Sarba',
    'Naccache',
    'Zouk Mosbeh',
    'Mkalles',
    'Antelias',
    'Sin El Fil',
    'Dbayeh',
    'Dora',
    'Zalka',
    'Jal El Dib',
    'Hazmieh',
    'Bsalim',
    'Awkar',
    'Fanar',
    'Rabieh',
    'Mazraat Yachouh',
    'Sarba',
    'Naccache',
    'Zouk Mosbeh',
    'Mkalles',
    'Antelias',
    'Sin El Fil',
    'Dbayeh',
    'Dora',
    'Zalka',
    'Jal El Dib',
    'Hazmieh',
    'Bsalim',
    'Awkar',
    'Fanar',
    'Rabieh',
    'Mazraat Yachouh',
    'Sarba',
    'Naccache',
    'Zouk Mosbeh',
    'Mkalles',
    'Antelias',
    'Sin El Fil',
    'Dbayeh',
    'Dora',
    'Zalka',
    'Jal El Dib',
    'Hazmieh',
    'Bsalim',
    'Awkar',
    'Fanar',
    'Rabieh',
    'Mazraat Yachouh',
    'Sarba',
    'Naccache',
    'Zouk Mosbeh',
    'Mkalles',
    'Antelias',
    'Sin El Fil',
    'Dbayeh',
    'Dora',
    'Zalka',
    'Jal El Dib',
    'Hazmieh',
    'Bsalim',
    'Awkar',
    'Fanar',
    'Rabieh',
    'Mazraat Yachouh',
    'Sarba',
    'Naccache',
    'Zouk Mosbeh',
    'Mkalles',
    'Antelias',
    'Sin El Fil',
    'Dbayeh',
    'Dora',
    'Zalka',
    'Jal El Dib',
    'Hazmieh',
    'Bsalim',
    'Awkar',
    'Fanar',
    'Rabieh',
    'Mazraat Yachouh',
    'Sarba',
    'Naccache',
    'Zouk Mosbeh',
    'Mkalles',
    'Antelias',
    'Sin El Fil',
    'Dbayeh',
    'Dora',
    'Zalka',
    'Jal El Dib',
    'Hazmieh',
    'Bsalim',
    'Awkar',
    'Fanar',
    'Rabieh',
    'Mazraat Yachouh',
    'Sarba',
    'Naccache',
    'Zouk Mosbeh',
    'Mkalles',
    'Antelias',
    'Sin El Fil',
    'Dbayeh',
    'Dora',
    'Zalka',
    'Jal El Dib',
    'Hazmieh',
    'Bsalim',
    'Awkar',
    'Fanar',
    'Rabieh',
    'Mazraat Yachouh',
    'Sarba',
    'Naccache',
    'Zouk Mosbeh',
    'Mkalles',
    'Antelias',
    'Sin El Fil',
    'Dbayeh',
    'Dora',
    'Zalka',
    'Jal El Dib',
    'Hazmieh',
    'Bsalim',
    'Awkar',
    'Fanar',
    'Rabieh',
    'Mazraat Yachouh',
    'Sarba'
  ];
const handleCityChange=(newChange)=>{
setCity(newChange)
onCityChange(newChange)
}
  return (
    <Box sx={{ width: 200}} >
      <Autocomplete
        disablePortal
        options={cities}
        renderInput={(params) => (
          <TextField {...params} label={<LocationCity sx={{color:"gray"}}/>} onchange={handleCityChange} value={city}    sx={{borderRadius:"15" ,color:"white"}}/>
        )}
    
      />
    </Box>
  );
}